name: 'rabbitmq-c'
version: 0.11.0
build:
  packages:
    rabbitmq-c:
  bits:
test:
  bits:
targets:
  default:
    main: 'main.c'
    build:
      packages:
        targets/unix/rabbitmq-c:
      includes:
        - /usr/local/opt/openssl/include
      cflags:
        - -DAMQ_PLATFORM=\\\"Darwin\\\"
        - -DHAVE_POLL
        - -DAMQP_BUILD
        - -DWITH_SSL=1
        - -Drabbitmq_EXPORTS
        - -DNDEBUG
        - -O3
        - -std=gnu90
        - -Wno-deprecated-declarations
      ldflags:
        - -L/usr/local/opt/openssl/lib
      libraries:
        - ssl
        - crypto
